### ISSUE TITLE
Unable to import GPG private key

### ISSUE THREAD

**Issue by riprasad** [crazy-max/ghaction-import-gpg#9]
#### Steps to reproduce this issue

1. Add PASSPHRASE and SIGNING_KEY as secret. 
    Follow below steps to get your SIGNING_KEY value:-
       - Run "gpg --list-secret-keys" and copy the ID of the key you'd like to use
       - Export the key with "gpg -a --export-secret-keys KEY_ID"(replace KEY_ID with your copied ID)
2. create the workflow [import-gpg.yaml](https://github.com/riprasad/gitub-actions-demo/blob/master/.github/workflows/import-gpg.yaml)
3. Push something to master branch to trigger the workflow

#### Expected behaviour

> The workflow should run successfully and the gpg private key should have been imported

#### Actual behaviour

> Workflow failed and gpg private key did not get imported ([output](https://github.com/riprasad/gitub-actions-demo/runs/646938049?check_suite_focus=true))

### Configuration

* Repository URL (if public): https://github.com/riprasad/gitub-actions-demo
* Build URL (if public): https://github.com/riprasad/gitub-actions-demo/runs/646938049?check_suite_focus=true

```yml
# paste your YAML workflow file here and remove sensitive data

name: import-gpg

on:
  push:
    branches: master

jobs:
  import-gpg:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v1
        with:
          git_gpgsign: true
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
```

### Logs

> Download the [log file of your build](https://github.com/riprasad/gitub-actions-demo/runs/646938049?check_suite_focus=true
[logs_263.zip](https://github.com/crazy-max/ghaction-import-gpg/files/4582686/logs_263.zip)
) and [attach it](https://help.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.

**Comment by crazy-max** [comment]
@riprasad Thanks for your report, I will try to reproduce your issue on another repo. Keep you in touch.

**Comment by riprasad** [comment]
@crazy-max I also tried the same workflow in one of my another repo, but the issue remained the same.

**Comment by crazy-max** [comment]
@riprasad Yes I was able to reproduce. Looks like transpiled code with openpgp is kinda broken.

**Comment by riprasad** [comment]
@crazy-max when can i expect the fix ?

**Comment by crazy-max** [comment]
@riprasad When I've got time. PR welcome.

**Comment by riprasad** [comment]
@crazy-max would have love to contribute but I am a Java Guy. No clue on Javascript/node.js

**Comment by crazy-max** [comment]
@riprasad Should be fixed now.

**Comment by riprasad** [comment]
@crazy-max Still failing https://github.com/riprasad/gitub-actions-demo/runs/648427979?check_suite_focus=true

**Comment by riprasad** [comment]
@crazy-max Thank you :)
